=== caporalesimone/Nyarlathotep/agent_json_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "client_name": {
            "type": "string"
        },
        "client_sw_version": {
            "type": "string",
            "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"
        },
        "hardware": {
            "type": "object",
            "properties": {
                "cpu_usage": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 100
                },
                "disk_total_GB": {
                    "type": "integer",
                    "minimum": 0
                },
                "disk_used_GB": {
                    "type": "integer",
                    "minimum": 0
                },
                "ram_total_MB": {
                    "type": "integer",
                    "minimum": 0
                },
                "ram_used_MB": {
                    "type": "integer",
                    "minimum": 0
                }
            },
            "required": ["cpu_usage", "disk_total_GB", "disk_used_GB", "ram_total_MB", "ram_used_MB"],
            "additionalProperties": false
        },
        "hostname": {
            "type": "string"
        },
        "json_version": {
            "type": "string",
            "pattern": "^[0-9]+\\.[0-9]+$"
        },
        "local_time": {
            "type": "string"
        },
        "net_interfaces": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "interface": {
                        "type": "string"
                    },
                    "ip_addresses": {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "pattern": "^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"
                        }
                    },
                    "mac": {
                        "type": "string",
                        "pattern": "^([0-9A-Fa-f]{2}-){5}[0-9A-Fa-f]{2}$"
                    }
                },
                "required": ["interface", "ip_addresses", "mac"],
                "additionalProperties": false
            }
        },
        "network_name": {
            "type": "string"
        },
        "os": {
            "type": "object",
            "properties": {
                "os_name": {
                    "type": "string"
                },
                "os_platform": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                }
            },
            "required": ["os_name", "os_platform", "uptime"],
            "additionalProperties": false
        },
        "users": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "idle_time": {
                        "type": "string",
                        "pattern": "^([0-9]+:[0-9]{2})$"
                    },
                    "logged": {
                        "type": "boolean"
                    },
                    "login_time": {
                        "type": "string",
                        "pattern": "^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/[0-9]{4} [0-2][0-9]:[0-5][0-9]$"
                    },
                    "session_id": {
                        "type": "string"
                    },
                    "session_name": {
                        "type": "string"
                    },
                    "status": {
                        "type": "string"
                    },
                    "username": {
                        "type": "string"
                    }
                },
                "required": ["idle_time", "logged", "login_time", "session_id", "session_name", "status", "username"],
                "additionalProperties": false
            }
        }
    },
    "required": ["client_name", "client_sw_version", "hardware", "hostname", "json_version", "local_time", "net_interfaces", "network_name", "os", "users"],
    "additionalProperties": false
}

=== caporalesimone/Nyarlathotep/nyarlathotep-backend/test/client_JSON_example.json
{
  "client_name": "Example",
  "client_sw_version": "1.6.2",
  "hardware": {
    "cpu_usage": 15.8,
    "disk_total_GB": 471,
    "disk_used_GB": 435,
    "ram_total_MB": 32495,
    "ram_used_MB": 12216
  },
  "hostname": "TD0262245",
  "json_version": "2.0",
  "local_time": "2024-09-06 21:41:24",
  "net_interfaces": [
    {
      "interface": "Ethernet 8",
      "ip_addresses": [
        "192.168.249.1",
		"192.168.249.2"
      ],
      "mac": "02-00-00-02-12-01"
    },
    {
      "interface": "Ethernet 10",
      "ip_addresses": [
        "141.86.197.114"
      ],
      "mac": "10-E7-C6-44-7A-65"
    },
    {
      "interface": "vEthernet (Default Switch)",
      "ip_addresses": [
        "172.30.128.1"
      ],
      "mac": "00-15-5D-1F-6D-4E"
    }
  ],
  "network_name": "TD0262245.domain.com",
  "os": {
    "os_name": "Windows 10",
    "os_platform": "Windows-10-10.0.19045-SP0",
    "uptime": "1d, 11:10:37"
  },
  "users": [
    {
      "idle_time": "3:48",
      "logged": false,
      "login_time": "05/09/2024 14:12",
      "session_id": "2",
      "session_name": "",
      "status": "Disc",
      "username": "F88899C"
    },
    {
      "idle_time": "5:56",
      "logged": false,
      "login_time": "06/09/2024 15:42",
      "session_id": "3",
      "session_name": "",
      "status": "Disc",
      "username": "C10585B"
    }
  ]
}
